# Generated by Django 6.0.3 on 2026-03-20 00:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to Supplier'), ('CONFIRMED', 'Confirmed by Supplier'), ('SHIPPED', 'Shipped'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('order_date', models.DateField()),
                ('expected_delivery_date', models.DateField()),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'suppliers_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_received', models.DecimalField(blank=True, decimal_places=2, help_text='Actual quantity received (may differ from ordered)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('batch_number', models.CharField(blank=True, help_text='Batch number from supplier', max_length=50)),
                ('expiration_date', models.DateField(blank=True, help_text='Expiration date for this batch', null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'suppliers_order_item',
                'ordering': ['ingredient__name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(help_text='Unit for this price (should match ingredient unit)', max_length=20)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, help_text='Leave blank for current price', null=True)),
                ('minimum_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum quantity for this price (tier pricing)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'suppliers_price',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('lead_time_days', models.IntegerField(default=7, help_text='Standard lead time in days for orders', validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_order_value', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order value in currency', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_terms', models.CharField(blank=True, help_text="Payment terms (e.g., 'Net 30', 'COD')", max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'suppliers_supplier',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='suppliers_s_name_6277a9_idx'), models.Index(fields=['is_active'], name='suppliers_s_is_acti_a75d30_idx')],
            },
        ),
    ]
