# Generated by Django 6.0.3 on 2026-03-20 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='supplierorderitem',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_order_items', to='inventory.ingredient'),
        ),
        migrations.AddField(
            model_name='supplierorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='suppliers.supplierorder'),
        ),
        migrations.AddField(
            model_name='supplierprice',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prices', to='inventory.ingredient'),
        ),
        migrations.AddField(
            model_name='supplierprice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='suppliers.supplier'),
        ),
        migrations.AddIndex(
            model_name='supplierorder',
            index=models.Index(fields=['supplier', 'status'], name='suppliers_o_supplie_26693e_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierorder',
            index=models.Index(fields=['status', 'order_date'], name='suppliers_o_status_c8ff60_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierorder',
            index=models.Index(fields=['order_number'], name='suppliers_o_order_n_9ccc96_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierorderitem',
            unique_together={('order', 'ingredient')},
        ),
        migrations.AddIndex(
            model_name='supplierprice',
            index=models.Index(fields=['supplier', 'ingredient'], name='suppliers_p_supplie_1647bc_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierprice',
            index=models.Index(fields=['ingredient', 'valid_from'], name='suppliers_p_ingredi_c7ce08_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierprice',
            index=models.Index(fields=['valid_from', 'valid_until'], name='suppliers_p_valid_f_c3b261_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierprice',
            unique_together={('supplier', 'ingredient', 'valid_from')},
        ),
    ]
