# Generated by Django 6.0.3 on 2026-03-20 00:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_location',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('WASTE', 'Waste'), ('TRANSFER', 'Transfer'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity moved (positive for IN, negative for OUT/WASTE)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_before', models.DecimalField(decimal_places=2, help_text='Stock quantity before this movement', max_digits=10)),
                ('quantity_after', models.DecimalField(decimal_places=2, help_text='Stock quantity after this movement', max_digits=10)),
                ('reason', models.TextField(help_text='Reason for this stock movement')),
                ('reference', models.CharField(blank=True, help_text='Reference number (e.g., order ID, production batch)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'inventory_stock_movement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('L', 'Liters'), ('mL', 'Milliliters'), ('units', 'Units'), ('pcs', 'Pieces'), ('boxes', 'Boxes')], max_length=20)),
                ('reorder_level', models.DecimalField(decimal_places=2, help_text='Minimum quantity before reordering is needed', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Standard cost per unit for calculations', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_ingredient',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='inventory_i_name_9e7294_idx'), models.Index(fields=['is_active'], name='inventory_i_is_acti_7e9e58_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Current quantity in stock', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('expiration_date', models.DateField(blank=True, help_text='Expiration date for this batch', null=True)),
                ('batch_number', models.CharField(blank=True, help_text='Batch or lot number for traceability', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_set', to='inventory.ingredient')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_set', to='inventory.location')),
            ],
            options={
                'db_table': 'inventory_stock',
                'ordering': ['expiration_date', 'created_at'],
            },
        ),
    ]
