# Generated by Django 6.0.3 on 2026-03-20 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stock'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['ingredient', 'location'], name='inventory_s_ingredi_120bff_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['expiration_date'], name='inventory_s_expirat_4a74b1_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['batch_number'], name='inventory_s_batch_n_527e87_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('ingredient', 'location', 'batch_number')},
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['stock', 'created_at'], name='inventory_s_stock_i_b959f7_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'created_at'], name='inventory_s_movemen_c713f8_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['created_by', 'created_at'], name='inventory_s_created_c2b0ec_idx'),
        ),
    ]
