# Generated by Django 6.0.3 on 2026-03-20 00:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_produced', models.DecimalField(decimal_places=2, help_text='Actual quantity produced', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('batch_number', models.CharField(help_text='Unique batch number for traceability', max_length=50, unique=True)),
                ('production_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recipes_production_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yield_quantity', models.DecimalField(decimal_places=2, help_text='Quantity of product this recipe yields', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('yield_unit', models.CharField(help_text='Unit of the yield (should match product unit)', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('instructions', models.TextField(blank=True, help_text='Step-by-step instructions for making this recipe')),
                ('prep_time_minutes', models.IntegerField(blank=True, help_text='Preparation time in minutes', null=True)),
                ('cook_time_minutes', models.IntegerField(blank=True, help_text='Cooking time in minutes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recipes_recipe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity of ingredient needed for the recipe yield', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('optional', models.BooleanField(default=False, help_text='Whether this ingredient is optional')),
                ('notes', models.CharField(blank=True, help_text='Special notes about this ingredient', max_length=200)),
            ],
            options={
                'db_table': 'recipes_recipe_ingredient',
                'ordering': ['ingredient__name'],
            },
        ),
    ]
