# Generated by Django 6.0.3 on 2026-03-20 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('products', '0001_initial'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionbatch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='products.product'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_ingredients', to='inventory.ingredient'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['product', 'is_active'], name='recipes_rec_product_bc1d99_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['is_active'], name='recipes_rec_is_acti_de97fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('product', 'version')},
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['recipe', 'production_date'], name='recipes_pro_recipe__0e72ce_idx'),
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['status', 'production_date'], name='recipes_pro_status_bbf99a_idx'),
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['batch_number'], name='recipes_pro_batch_n_7321a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipe', 'ingredient')},
        ),
    ]
