# Generated by Django 6.0.3 on 2026-03-20 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.customer'),
        ),
        migrations.AddField(
            model_name='customerorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.customerorder'),
        ),
        migrations.AddField(
            model_name='customerorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['customer', 'status'], name='orders_cust_custome_f72993_idx'),
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['status', 'order_date'], name='orders_cust_status_cef710_idx'),
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['order_number'], name='orders_cust_order_n_07ddd1_idx'),
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['requested_delivery_date'], name='orders_cust_request_cfc82d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customerorderitem',
            unique_together={('order', 'product')},
        ),
    ]
